version: '3'
tasks:
  clean:
    cmds:
      - echo "Cleaning"
      - rm -rf build-linux
      - rm -rf vcpkg
      - rm -rf vcpkg_installed
      - rm -rf build-windows
  build-linux:
    cmds:
      - echo "Building for Linux"
      - sudo rm -rf ./build-linux/deploy
      - rm deploy/*.AppImage || true
      - docker run -it -v "${PWD}:/home/user/project" stateoftheartio/qt6:6.6-gcc-aqt sh -c "chmod +x ./project/linux/docker-build.sh; ./project/linux/docker-build.sh"