version: '3'
tasks:
  clean:
    cmds:
      - echo "Cleaning"
      - sudo rm -rf build-linux
      - sudo rm -rf vcpkg
  build-linux:
    cmds:
      - echo "Building for Linux"
      - sudo rm -rf ./build-linux/deploy
      - docker run -it -v "${PWD}:/home/user/project" stateoftheartio/qt6:6.6-gcc-aqt sh -c "chmod +x ./project/linux/docker-build.sh; ./project/linux/docker-build.sh"